common/yak/yaklib/tools/nuclei.go
common/yakgrpc/yakit/yak_script.go

1. 修改使用脚本全名查询不出记录的问题
2. 修改 AllPoC() 接口查不出数据的问题

修复 Nuclei 脚本查询

---

common/crawlerx/TODO.md
common/crawlerx/newcrawlerx/README.md
common/crawlerx/newcrawlerx/check.go
common/crawlerx/newcrawlerx/cmd/param.ini
common/crawlerx/newcrawlerx/cmd/run.go
common/crawlerx/newcrawlerx/config.go
common/crawlerx/newcrawlerx/data.go
common/crawlerx/newcrawlerx/element.go
common/crawlerx/newcrawlerx/export.go
common/crawlerx/newcrawlerx/httpreq.go
common/crawlerx/newcrawlerx/main.go
common/crawlerx/newcrawlerx/manager.go
common/crawlerx/newcrawlerx/page.go
common/crawlerx/newcrawlerx/start.go
common/crawlerx/newcrawlerx/starter.go
common/crawlerx/newcrawlerx/tools.go
common/crawlerx/newcrawlerx/tree.go

解决无法获得扫描深度的问题
为爬虫更新报错的返回值
修复bug

add scan depth && fix bugs

---

common/crawlerx/TODO.md
common/crawlerx/newcrawlerx/README.md
common/crawlerx/newcrawlerx/action.go
common/crawlerx/newcrawlerx/check.go
common/crawlerx/newcrawlerx/collect.go
common/crawlerx/newcrawlerx/data.go
common/crawlerx/newcrawlerx/element.go
common/crawlerx/newcrawlerx/href_get.js
common/crawlerx/newcrawlerx/starter.go
common/crawlerx/newcrawlerx/text.go
common/crawlerx/newcrawlerx/tools.go
common/crawlerx/newcrawlerx/tree.go
common/crawlerx/newcrawlerx/vue.go

将vue使用的event listen爬虫方式与普通爬虫合并，现在不需要进行参数设置 会自动根据页面情况选择最优方式进行爬虫
通过正则表达式的方式对页面和js文件中的链接进行爬取
对于js中的链接，现在不会对js中的链接进行再次访问，会对这些链接进行标记

update event listener && text compiler get url

---

common/simulator/README.md
common/simulator/cmd/sub/example.go
common/simulator/core/constructor.go
common/simulator/core/eval.go
common/simulator/examples/bruteforce.go
common/simulator/examples/config.go
common/simulator/export.go
common/simulator/httpbrute/config.go
common/simulator/httpbrute/core.go
common/simulator/httpbrute/data.go
common/simulator/httpbrute/main.go
common/simulator/httpbrute/main_test.go
common/simulator/httpbrute/result.go
common/simulator/httpbrute/tools.go
common/yak/script_engine.go

重构了http模拟点击爆破 代码更合理 可以获取更多爆破过程信息

rebuild http brute in simulator

---

common/jsonpath/jsonpath.go
common/jsonpath/jsonpath_test.go
common/mutate/http_fuzz.go

fix param detail

---

common/crawlerx/newcrawlerx/action.go
common/crawlerx/newcrawlerx/cmd/param.ini
common/crawlerx/newcrawlerx/cmd/run.go
common/crawlerx/newcrawlerx/collect.go
common/crawlerx/newcrawlerx/config.go
common/crawlerx/newcrawlerx/element.go
common/crawlerx/newcrawlerx/export.go
common/crawlerx/newcrawlerx/page.go
common/crawlerx/newcrawlerx/req.go
common/crawlerx/newcrawlerx/result.go
common/crawlerx/newcrawlerx/starter.go
common/crawlerx/newcrawlerx/text.go
common/crawlerx/newcrawlerx/tools.go
common/crawlerx/newcrawlerx/vue.go

添加页面元素内容检查 && 修复全局超时
url正则匹配优化
事件点击触发方式更新

部分爬虫功能修复&&更新

---

common/simulator/config/config.go
common/simulator/core/constructor.go
common/simulator/core/element.go
common/simulator/core/start.go
common/simulator/export.go
common/simulator/httpbrute/config.go
common/simulator/httpbrute/core.go
common/simulator/httpbrute/main_test.go

修复重新输入用户名密码时的bug
新增等待图片加载时间
新增可执行浏览器参数

fix bug of char input && img loader waittime

---

common/crawlerx/README.md
common/crawlerx/action.go
common/crawlerx/config.go
common/crawlerx/data.go
common/crawlerx/exports.go
common/crawlerx/starter.go

add localstorage && customized invalid suffix of url
update readme.md

Add new params on crawlerx

---

common/simulator/config/config.go
common/simulator/config/data.go
common/simulator/core/constructor.go
common/simulator/core/start.go
common/simulator/export.go
common/simulator/httpbrute/config.go
common/simulator/httpbrute/core.go
common/simulator/httpbrute/main_test.go

add leakless config on httpbrute

add leakless config on httpbrute

---

common/simulator/core/constructor.go
common/simulator/core/start.go
common/simulator/examples/bruteforce.go
common/simulator/httpbrute/core.go
common/simulator/httpbrute/core_test.go
common/simulator/httpbrute/http.go
common/simulator/httpbrute/http_test.go
common/simulator/httpbrute/main.go
common/simulator/httpbrute/main_test.go

为模拟点击爆破添加新的报错信息

---

common/utils/lowhttp/debug_test.go
common/yak/httptpl/yaktpl_extractor.go
common/yakgrpc/grpc_fuzzer_test.go

fix(extractor) matcher result

---

common/crep/static/navtab.html

add(mitm) 添加快捷键提示

---

.github/workflows/essential-tests.yml
common/pcapx/builder.go
common/pcapx/link.go

don't exit if ethernet not existed

fix(pcapx): make it run on action

---

common/chaosmaker/chaos_test.go
common/chaosmaker/dns.go
common/chaosmaker/http.go
common/chaosmaker/icmp.go
common/chaosmaker/tcp.go
common/chaosmaker/udp.go
common/suricata/data/numrange/numrange.go
common/suricata/data/numrange/numrange_test.go
common/suricata/generate/generator.go
common/suricata/generate/icmp.go
common/suricata/generate/tcp.go
common/suricata/match/http.go
common/suricata/match/icmp.go
common/suricata/match/match.go
common/suricata/match/tcp.go
common/suricata/rule/layers.go
common/suricata/rule/model.go
common/suricata/rule/visitor_addr.go
common/suricata/rule/visitor_param.go
go.mod

feat(chaosmaker): support icmp

---

common/crawlerx/config.go
common/crawlerx/starter.go
common/crawlerx/utils.go
common/crawlerx/utils_test.go

fix(crawlerx):headers & cookies custom set not working

fix(crawlerx):headers & cookies custom set not working

---

common/yakgrpc/grpc_managePayload.go

fix(payload):去除payload尾部的非空格空白符

---

common/yak/yaktest/mustpass/files/risk_output_limit.yak
common/yakgrpc/yakit/exportresource.go
common/yakgrpc/yakit/risk_exports.go

https://github.com/yaklang/yakit/issues/1012

fix(risk) limit risk input size

---

common/yakgrpc/grpc_execBatchYakScript.go
common/yakgrpc/grpc_execBatchYakScript_batch_exec.yak
common/yakgrpc/grpc_execBatchYakScript_test.go

fix(batch-yak-script):修复批量执行插件代理设置无效的问题

---

common/yak/httptpl/yaktpl_variables.go
common/yakgrpc/grpc_fuzzer.go
common/yakgrpc/grpc_fuzzer_test.go

1. add raw type for variables
Reference: https://github.com/yaklang/yakit/pull/1044

feat: support raw type for fuzzer params

---

common/utils/str_utils.go
common/utils/str_utils_test.go

glob.Compile 出来的是从头匹配而不是contains，加个"*"救一下

fix(mitm): url filter

---

common/crep/mitm_hijack_handler.go
common/minimartian/v3/proxy.go
common/utils/http_dumper.go
common/utils/lowhttp/httpctx/base.go
common/yakgrpc/grpc_mitm_plainproxy_test.go

优化了非 HTTPS 代理的时候，直接在 URI 中写 URL 的情况

improve plain http proxy without proxy-conn

---

common/yak/httptpl/config.go
common/yak/httptpl/exports.go
common/yak/httptpl/exports_test.go
common/yak/httptpl/nuclei.go
common/yak/httptpl/nuclei_test.go
common/yak/httptpl/yaktpl.go
common/yak/httptpl/yaktpl_exec.go

新增了 httptpl 的 SelfContained 的字段，新增了 QueryAll 的新选项优化了
移除了无用的测试，新增了 OnTemplateLoaded 和相关测试

add all() params and skip self-contained

---

common/finscan/app.go
common/pcapx/arpx/arp.go
common/synscan/app.go
common/synscan/create_packets.go
common/utils/netutil/netroute/common.go
common/yak/yaktest/mustpass/files/synscan_openvpn_mock.yak
common/yak/yaktest/mustpass/mustpass_base_test.go

修复 SYN 扫描中在 VPN 情形下遇到的 BUG
1. 路由因为某些奇怪的原因出错
2. UTUN 的链路类型应该为 Loopback 的类型

fix bug in route and vpn case

---

common/yakgrpc/grpc_tunnel.go

https://github.com/yaklang/yakit/issues/1082

fix(dnslog) custom script timestamp bug

---

common/yak/antlr4Lua/exec_test.go
common/yak/antlr4Lua/executor.go
common/yak/antlr4Lua/infrastructure/buildin_operators.go
common/yak/antlr4Lua/luaast/function.go
common/yak/antlr4Lua/luaast/generate_vmcode.go
common/yak/antlr4Lua/official_test.go
common/yak/antlr4yak/yakvm/vm_exec.go

- change to new lua operator api
- merge vm_exec/OpPushRef Lua and Yak
- complete Import functions
- copy closure function when create

Fix/lua[closure scope\buildin\OpcodePushr\exec_test]

---

common/suricata/match/dns.go
common/suricata/match/filedata.go
common/suricata/match/group.go
common/suricata/match/group_test.go
common/suricata/match/http.go
common/suricata/match/icmp.go
common/suricata/match/match.go
common/suricata/match/match_test.go
common/suricata/match/payload.go
common/suricata/match/tcp.go
common/suricata/match/udp.go

- suricata 规则预编译到 workflow
- httpMatcher 规则同时应用到 ordinalMatcher
- 新增 Matcher 实例池，提升匹配的并行度
- 修复了 fastpattern 的 ci 不稳定的问题

feat(suricata): compile rule

---

common/chaosmaker/chaos_test.go

补 groupMatcher 在 chaosmaker 的测试

test(chaosmaker): cross verify suricata group matcher

---

common/yak/yaktest/mustpass/files/risk_output_limit.yak
common/yakgrpc/yakit/risk_exports.go

add(risk) details limit

---

common/netx/dialx_force_proxy.go
common/utils/func_helper.go
common/utils/func_helper_test.go
common/utils/os_utils.go
common/yak/httptpl/exports.go
common/yakgrpc/grpc_config_global_network_test.go
common/yakgrpc/grpc_duplex_conn.go
common/yakgrpc/grpc_execBatchYakScript_test.go
common/yakgrpc/grpc_mitm_proxy_test.go
common/yakgrpc/grpc_pcapx.go
common/yakgrpc/yakgrpc.proto
common/yakgrpc/ypb/yakgrpc.pb.go
common/yakgrpc/ypb/yakgrpc_grpc.pb.go

1. 增加服务端推送的接口
2. 增加防抖和截流，并且把它用在双向流中
3. 增加了 Int64 和 Int32 Safe 的表达式计算 Helper

pcapx: add statistics response for PcapX, add server push(duplex conn)

---

common/yak/ssa/builder.go
common/yak/ssa/call.go
common/yak/ssa/disasm.go
common/yak/ssa/emit.go
common/yak/ssa/error_message.go
common/yak/ssa/func.go
common/yak/ssa/instruction.go
common/yak/ssa/object.go
common/yak/ssa/ssa.go
common/yak/ssa/type.go
common/yak/ssa/use.go
common/yak/ssa/value.go
common/yak/ssa/variable.go
common/yak/ssa4analyze/error_message.go
common/yak/ssa4analyze/pass/block_condition.go
common/yak/ssa4analyze/pass/error_message.go
common/yak/ssa4analyze/pass/type_inference.go
common/yak/ssa4analyze/type_check.go
common/yak/static_analyzer_test.yak
common/yak/yak2ssa/builder.go
common/yak/yak2ssa/builder_ast.go
common/yak/yak2ssa/error_message.go
common/yak/yak2ssa/ssa_error_test.go
common/yak/yak2ssa/ssa_vars_test.go

> - [x] 增加map的member call的报错信息
> - [x] 增加slice的slice call的报错信息
> - [x] 增加闭包函数调用函数绑定时的检查

[Feature] ssa collect and  rewrite error message 

---

common/yak/ssa/variable.go
common/yak/static_analyzer.go
common/yakgrpc/grpc_smoking_evaluate_plugin.go
common/yakgrpc/grpc_smoking_evaluate_plugin_test.go

* 在SmokingEvaluatePlugin接口区分静态分析结果的危险程度
* 标记静态分析的错误来源
* 全局禁用编译器的严格模式，使用SSA进行错误分析
* 增加对应的测试文件

[Fix] smoking plugin and static analyze function 

---

common/yak/ssa/error.go
common/yak/ssa/error_message.go
common/yak/ssa/extern_instance.go
common/yak/ssa/object.go
common/yak/ssa/ssa.go
common/yak/ssa/type.go
common/yak/ssa4analyze/error_message.go
common/yak/ssa4analyze/type_inference.go
common/yak/yak2ssa/builder.go
common/yak/yak2ssa/builder_ast.go
common/yak/yak2ssa/ssa_error_test.go

* 修改field检查的报错信息，并尝试对错误的Key获取相似数据
* 修正获取数据时大小写导致的错误匹配
* 支持新的注释选项，可以部分(`@ssa-ignore`)或完全(`@ssa-nocheck`)关闭SSA检查。

[feature] SSA field check and new line commend rule

---

common/crawlerx/README.md
common/crawlerx/action.go
common/crawlerx/config.go
common/crawlerx/exports.go
common/crawlerx/main_test.go
common/crawlerx/screenshot.go
common/crawlerx/screenshot_test.go
common/crawlerx/starter.go

add screenshot on target url
fix select element & textarea element not working
update readme.md

feat(crawlerx):add screenshot

---

common/yak/JS2ssa/builder.go
common/yak/JS2ssa/builder_ast.go
common/yak/JS2ssa/builder_test.go
common/yak/ssa/variable.go

fix some small bugs include:
- block.skip influence the phi value
- singleExpression need to handle ( )

Fix Js2ssa

---

common/simulator/httpbrute.go

fix panic of 32000 in devtools
add a sleep time when visit window.location.href in js temporarily
fix panic of captcha check without captcha detect url

fix(simulator): fix panic of location href jump in js

---

common/yak/ssa/InstructionEmit.go
common/yak/ssa/builder.go
common/yak/ssa/extern_instance.go
common/yak/ssa/func.go
common/yak/ssa/instruction.go
common/yak/ssa/ssa.go
common/yak/ssa/type.go
common/yak/ssa4analyze/error_message.go
common/yak/ssa4analyze/type_check.go
common/yak/ssa4analyze/type_inference.go
common/yak/yak2ssa/builder_ast.go

[Fixup&Refactor] ssa call argument typechek \ defer block \ type method

---

common/yak/JS2ssa/builder_ast.go
common/yak/ssa/InstructionEmit.go
common/yak/ssa/InstructionOpcode.go
common/yak/ssa/builder.go
common/yak/ssa/cfg.go
common/yak/ssa/disasm.go
common/yak/ssa/extern_instance.go
common/yak/ssa/type.go
common/yak/ssa/variable.go
common/yak/ssa4analyze/block_condition.go
common/yak/ssa4analyze/error_message.go
common/yak/ssa4analyze/type_check.go
common/yak/ssa4analyze/type_inference.go
common/yak/ssa_parse.go
common/yak/ssaapi/ssa_exports.go
common/yak/static_analyzer.go
common/yak/yak2ssa/builder_ast.go
common/yak/yak2ssa/builder_literal.go
common/yak/yak2ssa/builder_object.go
common/yak/yak2ssa/ssa_error_test.go
common/yak/yak2ssa/ssa_vars_test.go

[Feature] ssa support buildin method and fixup cfg scope

---

common/crawlerx/action.go
common/crawlerx/utils.go

更改select元素中的option元素发现方式（关键词发现改为selector发现）

fix(crawlerx): option element not found

---

common/yak/yaklib/sync.go

feat(sync): NewPool access optional newFunc argument

doc(sync):

---

common/fp/webfingerprint/datasource.go
common/utils/regen/regen.go
common/utils/regen/regen_test.go
common/yak/yaklib/regen.go
common/yak/yaklib/tcp.go
common/yak/yaklib/udp.go

refactor(regen): GenerateOne return string instead of slice

doc(regen):

---

common/yak/ssa/ssa.go
common/yak/yak2ssa/ssa_vars_test.go

fix the change phi in position

fixup(phi_position)fix phi position

---

common/crawlerx/main_test.go
common/crawlerx/router.go
common/crawlerx/router_test.go
common/crawlerx/starter.go

fix invalid url panic
fix running goroutine when close crawlerx

fix(crawlerx): invalid url panic

---

common/yak/antlr4yak/builtin_functions.go
common/yak/antlr4yak/engine.go
common/yak/antlr4yak/yakvm/func.go
common/yak/antlr4yak/yakvm/op_call.go
common/yak/antlr4yak/yakvm/value_call.go
common/yak/antlr4yak/yakvm/virtual_machine.go
common/yak/yakdoc/func_utils.go
common/yak/yaktest/mustpass/files/eval.yak
common/yak/yaktest/mustpass/files/waitAllAsyncCallFinish.yak
common/yak/yaktest/mustpass/files/waitAllAsyncCallFinish2.yak

feat(yakvm-context-function): waitAllAsyncCallFinish

refactor(yakvm-context-function):

---

common/yak/plugin_type_analyzer/plugin_type_analyzer.go
common/yak/plugin_type_analyzer/yak_analyzer.go
common/yak/ssaapi/program.go
common/yak/ssaapi/ssa_exports.go
common/yak/ssaapi/type.go
common/yak/ssaapi/use_def_chain.go
common/yak/ssaapi/values.go
common/yak/static_analyzer.go
common/yakgrpc/grpc_smoking_evaluate_plugin.go
common/yakgrpc/grpc_yaklang_inspect_information.go

[Refactor] StaticAnalyzer supoort plugin type

---

common/utils/os_utils.go
common/yak/yaklib/yakit.go
common/yakgrpc/server.go

https://github.com/yaklang/yakit/blob/0ed4d2f9692ce0bc60024b6251d62ee924058e0a/app/main/handlers/yakLocal.js#L91

前端引擎端口不正确的bug

---

common/yak/antlr4util/range.go
common/yak/yak2ssa/range.go

fix(antlr2util): check token nil

---

common/yak/JS2ssa/builder_test.go
common/yak/ssa/disasmLine.go
common/yak/ssa/scope.go
common/yak/ssa/ssa.go
common/yak/ssa4analyze/type_inference.go
common/yak/ssaapi/values.go
common/yak/yak2ssa/ssa_vars_test.go

refactor(ssa): refactor DisasmLine avoid stack overflow

---

common/yak/yaklib/json.go

feat(json): export withPrefix, withIndent, dumps allow options

doc(json):

---

.github/workflows/generate-web-doc.yml

use yarn version --minor instead --patch

refactor(ci): generate-web-doc

---

common/yak/antlr4yak/executor_test.go
common/yak/antlr4yak/yakast/for.go

fix(vm): fix for-range with self modified not work

---

common/yak/ssa/variable.go
common/yak/yak2ssa/ssa_error_test.go

allow variable assigned by extern instance be FreeValue

[fix] ssa CanBuildFreeValue 

---

common/yak/plugin_type_analyzer/ssa_option/yak_options.go
common/yak/plugin_type_analyzer/test/option_yak_test.go
common/yak/yak2ssa/builder_object.go

* this method parameter should [number, fieldType]

[Fix]:buildIn method "slice.Insert" 

---

common/yakgrpc/grpc_fuzzer.go

release switch when stream context close

fix(webfuzzer):

---

common/yak/plugin_type_analyzer/information.go/cli_parameter.go

[refactor] cli parameter return front-end render type

---

.github/workflows/essential-tests.yml
common/utils/env_github_ci.go
common/yakgrpc/util.go

[refactor] don't have to  create environment variable

---

common/vulinbox/db.go
common/vulinbox/html/mall/vul_mall_cart.html
common/vulinbox/html/mall/vul_mall_order.html
common/vulinbox/html/mall/vul_mall_userProfile.html
common/vulinbox/model_mall_usercart.go
common/vulinbox/model_mall_userorder.go
common/vulinbox/route.go
common/vulinbox/vul_mall_userCart.go
common/vulinbox/vul_mall_userOrder.go

add order page

---

common/yakgrpc/grpc_fuzzer.go

solve problem of fuzztag sync test ci

fix httpfuzzer

---

common/utils/faviconhash.go
common/utils/faviconhash_test.go
common/utils/htmlquery/exports.go
common/yak/yaklib/httpex.go
go.mod
go.sum
go.work.sum

[Feat] Add GetFaviconURL Function

---

common/yak/ssa/disasmLine.go
common/yak/static_analyzer/information/risk.go
common/yak/static_analyzer/rules/risk_rules.go
common/yakgrpc/grpc_yaklang_inspect_information_test.go
common/yakgrpc/yakit/risk_exports.go

feat(ssa-rules): check risk type is valid
feat(lib-risk): restrict risk type

restrict risk type

---

common/crawlerx/config.go
common/crawlerx/exports.go
common/crawlerx/starter.go
common/yak/yak_to_caller_manager.go
common/yak/yaktest/mustpass/files/crawlerx.yak

fix runtimeid not in crawlerx when running in yakit

 fix(crawlerx): fix runtimeid in crawlerx

---

common/crawlerx/config.go
common/crawlerx/exports.go
common/crawlerx/main.go

feat(crawlerx): add url check config

---

common/yakgrpc/grpc_fuzzer_render.go
common/yakgrpc/grpc_mitm.go
common/yakgrpc/grpc_mitm_saveflow_test.go
common/yakgrpc/yakit/httpflow.go

will fix body first if different boundary

fix(httpflow):

---

common/yakgrpc/grpc_managePayload.go

remove duplicate payloads write other file first

fix(grpc_payload):

---

common/crawlerx/config.go
common/crawlerx/data.go
common/crawlerx/starter.go
common/yak/cmd/yakcmds/crawlerx.go
common/yak/cmd/yakcmds/scan.go

set localstorage save before crawlerx start
update crawlerx in yak cmd

fix(crawlerx): update yak cmd

---

common/minimartian/lowhttp_exec.go
common/yak/yaklib/mitm.go
common/yak/yaktest/mustpass/files/mitm_downstream_modified_request.yak
common/yak/yaktest/mustpass/mustpass_base_test.go

mitm set downstream proxy to other mitm will cause use raw request but not modified request by first mitm hijackRequest

fix(lib-mitm):

---

common/utils/lowhttp/http_struct/http_struct.go
common/yak/yak_to_caller_manager.go
common/yak/yaklib/yakhttp/base.go
common/yak/yaklib/yakhttp/base_test.go
common/yakgrpc/grpc_http_request_debug_test.go

add plugin context options
refactor HTTPConfig, use PocConfigOption directly

feat&refactor(lib-http):

---

common/utils/pprofutils/config.go
common/utils/pprofutils/cpuprofile.go
common/utils/pprofutils/exports.go
common/utils/pprofutils/memprofile.go
common/yak/script_engine.go

```
❯ go run common/yak/cmd/yak.go -c 'pprof.StartCPUProfile(pprof.timeout(10), pprof.callback(i => dump(i)))'
(string) (len=60) "/Users/.../yakit-projects/temp/cpu-20240328_15_15_46.prof"
```

add profile interface in yaklang

---

common/simulator/filter.go
common/simulator/httpbrute.go
common/simulator/matrix.go

修复在所有目标元素发现后仍在寻找元素的bug
优化验证码元素找寻的逻辑

fix(simulator): fix bugs on target element search

---

.github/workflows/essential-tests.yml
common/crawlerx/config.go
common/crawlerx/exports.go
common/crawlerx/preaction/pre.go
common/crawlerx/preaction/pre_test.go
common/crawlerx/starter.go
common/simulator/config.go
common/simulator/element.go
common/simulator/exports.go
common/simulator/httpbrute.go

add pre action on bruteforce
add session storage on crawlerx
fix null point bug on crawlerx

feat(simulator): add pre action on bruteforce

---

common/yak/httptpl/config.go

EnableReverseConnectionFeature default true

refactor(httptpl):set enableReverseConnectionFeature default true

---

common/openapi/openapigen/path.go
common/utils/lowhttp/modifier.go
common/utils/lowhttp/modifier_test.go
common/utils/lowhttp/poc/poc.go
common/utils/lowhttp/query.go
common/utils/lowhttp/query_test.go
common/yak/yaklib/csrf.go
common/yak/yaklib/csrf_test.go
common/yakgrpc/grpc_fuzzer.go
common/yakgrpc/grpc_fuzzer_test.go
common/yakgrpc/grpc_generate_yak_code_test.go
common/yakgrpc/yakgrpc_test.go

refactor GenerateCSRFPoc
fix GetParamsFromBody, support same key

refactor CSRF POC && fix GetParamsFromBody

---

common/yak/yakurl/fs.go
common/yakgrpc/grpc_request_yak_url_test.go

result dir HaveChildrenNodes should be true only when dir is not empty

fix&refactor(yakurl-fs):

---

common/utils/lowhttp/poc/poc.go

username and password options
remove default option because lowhttp config has same default options

fix&feat(lib-poc):

---

common/pcapx/pcaputil/reassembly.go
common/yakgrpc/grpc_assets_test.go
common/yakgrpc/grpc_fuzzer.go
common/yakgrpc/yakit/fuzzer_task.go

association delete fuzzer-response when delete fuzzer-task

feat(grpc-fuzzer-task):

---

common/consts/yakit.go
common/coreplugin/smuggle_test.go
common/crep/mitm_config.go
common/crep/mitm_transparent_ssl.go
common/fp/webfingerprint/fetcher.go
common/mutate/http_pool.go
common/schema/httpflow.go
common/utils/http_response_builder.go
common/utils/lowhttp/exec.go
common/utils/lowhttp/save_handler.go
common/utils/lowhttp/ws_client.go
common/yakgrpc/grpc_fuzzer.go
common/yakgrpc/grpc_mitm.go
common/yakgrpc/grpc_mitm_large_response_test.go
common/yakgrpc/yakit/httpflow.go

lowhttp allow save too large response
unify fuzzer too-large-response handler and lowhttp too-large-response handler

feat(lowhttp):

---

common/mutate/fuzztag.go
common/mutate/fuzztag_test.go

date,datetime,date:range support timezone

feat(fuzztag):

---

common/utils/lowhttp/http_request.go
common/utils/lowhttp/http_request_test.go

multipart fix content-type should keep other params
Fixes yaklang/yakit#1744

fix(utils-FixHTTPPacketCRLF):

---

common/yak/ssaapi/exclusive_z_top_defs.go
common/yak/ssaapi/test/php/cmdinj_test.go

getTopDefs append nil value when meet strange parameter

fix(ssa): getTopDefs append nil value when meet strange parameter

---

common/yak/yaklib/base_funcs.go

feat(lib-global): praseInt with base

---

common/syntaxflow/sfvm/frame.go
common/syntaxflow/sfvm/value_list.go
common/syntaxflow/sfvm/value_op.go
common/syntaxflow/sfvm/vm.go
common/yak/ssaapi/sf_config.go
common/yak/ssaapi/sf_prog.go
common/yak/ssaapi/sf_query.go
common/yak/ssaapi/sf_value.go
common/yak/ssaapi/sf_values.go
common/yak/ssaapi/test/syntaxflow/config_filter_test.go

1.增加config语句建立新的vm的时候，将旧的vm的信息传递给新的vm。

feat(syntaxflow):add env info when the new vm created within old vm

---

common/mutate/http_pool.go
common/utils/lowhttp/config.go
common/utils/lowhttp/exec.go
common/yakgrpc/grpc_fuzzer_hotpath_test.go
common/yakgrpc/grpc_utils_test.go

after-request handler not change httpflow record

fix(httppool):

---

common/mutate/http_fuzz.go
common/mutate/http_fuzz_handlers.go

fix(fuzz): concurrent write

---

common/yak/java/java2ssa/builder.go
common/yak/java/java2ssa/visit_entry.go
common/yak/java/java2ssa/visit_stmt_block_expr.go
common/yak/php/php2ssa/visit_cls.go
common/yak/php/php2ssa/visit_stmt.go
common/yak/ssa/blue_print.go
common/yak/ssa/builder.go
common/yak/ssa/database_cache.go
common/yak/ssa/database_code.go
common/yak/ssa/database_profile.go
common/yak/ssa/database_type.go
common/yak/ssa/func.go
common/yak/ssa/instructionLazy.go
common/yak/ssa/return.go
common/yak/ssa/ssa.go
common/yak/ssa/ssa_predefined.go
common/yak/ssa/ssadb/code.go
common/yak/ssa/ssadb/stats.go
common/yak/ssa/type.go
common/yak/ssaapi/exclusive_z_top_defs.go
common/yak/ssaapi/values.go

Refactor[ssa] use Point/Pointer replace Reference/TypeReturnValue 

---

common/netx/tlsinspect.go

feat(tls): Inspect add some result fields

---

.github/workflows/new-yak-engine-test.yml
common/yak/antlr4yak/yakvm/vm_panic.go

use editor.GetTextContextWithPrompt for panic message

fix(vm-panic):

---

common/crep/mitm_ws.go
common/utils/lowhttp/poc/poc.go
common/utils/lowhttp/ws_client.go
common/utils/lowhttp/ws_test.go
common/vulinboxagentclient/client.go
common/yakgrpc/grpc_mitm_websocket_test.go
common/yakgrpc/grpc_wsfuzzer.go

feat(ws-fuzzer): add context

---

common/minimartian/lowhttp_exec.go
common/minimartian/mitmloop.go
common/yakgrpc/grpc_mitm_test.go

send to real host although without connect request when change Host header

fix(mitm): send to real host although without connect request when change Host header

---

common/simulator/captcha.go
common/simulator/captcha_test.go
common/simulator/config.go
common/simulator/data.go
common/simulator/exports.go
common/simulator/httpbrute.go
common/simulator/main_test.go
go.work.sum

匹配新的ddddocr接口模式 目前同时兼容新老接口 之前代码无需修改不影响使用

feat(simulator): update new dddd ocr api interface

---

common/coreplugin/base-yak-plugin/修改 HTTP 请求 Cookie.yak
common/coreplugin/base-yak-plugin/修改 HTTP 请求 Header.yak

在hijackSaveHTTPFlow 保存流量的时候设置fromPlugin

feat(httpflow):modify interactive plugin to have 'FromPlugin'

---

common/mutate/http_pool.go
common/yakgrpc/grpc_fuzzer.go
common/yakgrpc/grpc_fuzzer_sequence.go
common/yakgrpc/grpc_fuzzer_sequence_test.go

1. fix concurrent send which make test sometimes fail
2. fix swg wait after add, use externSwg to control overall concurrency

fix(grpc-fuzzer-sequence)

---

common/yak/java/java2ssa/visit_stmt_block_expr.go
common/yak/java/tests/member_test.go
common/yak/java/tests/oop_test.go
common/yak/ssa/blue_print.go
common/yak/ssa/member_call.go
common/yak/ssaapi/test/java/basic_test.go
common/yak/ssaapi/test/java/default_obj_method_call_test.go
common/yak/ssaapi/test/java/interface_test.go

fix(java2ssa):should use member var though having no this

---

common/crawlerx/check.go
common/crawlerx/data.go
common/crawlerx/exports.go
common/crawlerx/main_test.go
common/crawlerx/starter.go
common/crawlerx/utils.go
common/simulator/browser.go

将headless替换成new headless 经过测试对老版本chrome应该没有影响
新增无限制域名扫描

feat(crawlerx): 将headless模式替换成new headless模式

---

common/domainextractor/extractdomain.go
common/yak/antlr4Lua/infrastructure/buildin_operators.go
common/yak/antlr4Lua/luaast/generate_vmcode.go
common/yak/antlr4nasl/executor/buildin_operators.go
common/yak/antlr4nasl/visitors/push_opcode.go
common/yak/antlr4yak/buildin_operators.go
common/yak/antlr4yak/dap/session.go
common/yak/antlr4yak/executor_test.go
common/yak/antlr4yak/yakast/generate_vmcode.go
common/yak/antlr4yak/yakvm/opcodes_marshal.go
common/yak/antlr4yak/yakvm/value.go
common/yak/antlr4yak/yakvm/value_call.go
common/yak/antlr4yak/yakvm/vm_exec.go
common/yak/yaklib/strings.go

ExtractDomain:
1. no decode ExtractDomain input default
VM:
1. simple value literal not use fmt.Sprint
2. add value.GetLiteral function

perf(vm,ExtractDomain):

---

common/yak/go2ssa/test/func_scope_test.go
common/yak/ssa/error_message.go
common/yak/ssa/ssa.go
common/yak/ssa/ssa_predefined.go
common/yak/ssa/value.go

改了一下globalvalue的逻辑，现在globalvalue可以生成phi了

fix globalvalue phi and add test

---

common/yak/cmd/yakcmds/ssacli.go
common/yak/ssa/ssadb/ssa_program.go
common/yak/ssaapi/language_parser.go

fix(ssa-cli):fix re-compile will not delete profile database

---

common/yak/go2ssa/builder_ast.go
common/yak/go2ssa/test/func_scope_test.go
common/yak/ssa/builder.go
common/yak/ssa/value.go
common/yak/ssaapi/test/golang/golang_template_test.go

改了下global value的逻辑，现在是在PushFunction将所有的global value拷贝到本地的scope中，然后在PopFunction中peek出来并放回global value

fix/ssa/global-scope: fix global

---

common/yak/go2ssa/builder_ast.go
common/yak/go2ssa/builder_literal.go
common/yak/go2ssa/test/side_effect_test.go
common/yak/ssa/call.go
common/yak/ssaapi/test/golang/golang_func_test.go
common/yak/ssaapi/test/golang/golang_side_effect_test.go
common/yak/ssaapi/test/yak/exclusive_side_effect_test.go

fix/ssa/site-effect - fix bug

---

common/coreplugin/base-yak-plugin/SQL注入-时间盲注-Sleep.yak
common/schema/httpflow.go
common/schema/risk.go
common/schema/utils_broadcast_data.go
common/schema/yak_script.go
common/yak/hook_mixed_plugin_caller.go
common/yak/yak_to_caller_manager.go
common/yakgrpc/grpc_httpflow_test.go
common/yakgrpc/grpc_mitm.go
common/yakgrpc/yakit/duplex_conn.go
common/yakgrpc/yakit/httpflow.go

close pluginFinishCh even if not call HijackSaveHTTPFlow

fix(mitm-replacer):

---

common/yak/ssa/cfg.go

fix HandlerReturnPhi

---

common/yakgrpc/grpc_mitm_replacers.go
common/yakgrpc/grpc_mitm_replacers_test.go

fix(grpc_mitm_replacers):

---

common/pcapx/pcaputil/open_device.go
common/synscanx/scanx.go
common/vulinbox/html/vul_sqli.html
common/yak/yaklib/tools/synscanx.go

npcap 1.6.0 版本下
wireshark 设备列表显示 loopback 无地址，但是可以正常的抓包，就想着尝试 mock 一下

fix windows empty loopback addresses

---

common/yakgrpc/grpc_mitm_filter_test.go
common/yakgrpc/grpc_mitm_proxy_test.go
common/yakgrpc/grpc_mitm_test.go

TestGRPCMUSTPASS_MITM_Runtime_Proxy
TestGRPCMUSTTPASS_MITM_HijackTags

test(grpc_mitm): try to fix some test

---

common/yak/php/php2ssa/visit_func.go
common/yak/php/php2ssa/visit_global.go
common/yak/ssaapi/analyze_context.go
common/yak/ssaapi/analyze_cross_process.go
common/yak/ssaapi/exclusive_z_bottom_use.go
common/yak/ssaapi/exclusive_z_top_defs.go
common/yak/ssaapi/test/syntaxflow/top_user_recursive_test.go

- Determine whether it is possible to cross process when analyzing values, rather than judging under each SSA symbol
- Separate the logic for analyzing the required call stack information and recording cross process behavior

refactor(ssaapi):refactor analyze-cross-process and top-def

---

common/syntaxflow/sfvm/frame.go
common/yak/ssaapi/sf_dataflow.go
common/yak/ssaapi/test/syntaxflow/config_filter_test.go
common/yak/ssaapi/test/syntaxflow/find_path_test.go
common/yak/ssaapi/values_graph_path.go

feat(sf):add destination value for native-call dataflow and support DFS

feat(sf):add destination value for native-call dataflow and support DFS

---

common/yak/go2ssa/builder.go
common/yak/go2ssa/builder_ast.go
common/yak/go2ssa/builder_express.go
common/yak/ssaapi/test/golang/golang_import_test.go

为golang import package添加了fulltypenames

fix(go2ssa): add fulltypenames for import package

---

common/simulator/README.md
common/simulator/config.go
common/simulator/exports.go
common/simulator/main.go
common/simulator/simple/config.go
common/simulator/simple/constructor.go
common/simulator/simple/page.go

支持等待页面加载直到某元素出现 避免过长的加载时间（更新信息可以不写这个 满足客户需求更新的组件）

feature(simulator): wait load before meet target element

---

common/utils/str_utils.go
common/yak/httptpl/nuclei_utils.go
common/yak/httptpl/yaktpl_extractor.go
common/yakgrpc/grpc_fuzzer_sequence_test.go

only one extractor results will set type to string instead of []string

feat(fuzzer_seq):

---

common/yakgrpc/yakit/httpflow.go
common/yakgrpc/yakit/httpflow_test.go

status code add new restrictions

refactor(grpc_query_httpflows):

---

common/crawlerx/starter.go
common/simulator/browser.go

set chrome --disable-features=HttpsUpgrades to avoid http url to https by chrome

fix(crawlerx): add chrome disable-features HttpsUpgrades

---

common/syntaxflow/sfbuildin/buildin/buildin-rule-test/scan_test.go
common/syntaxflow/sfbuildin/buildin/java/cwe-22-path-travel/java-direct-path-travel.sf
common/yak/ssaapi/exclusive_z_bottom_use.go
common/yak/ssaapi/exclusive_z_top_defs.go
common/yak/ssaapi/program.go
common/yak/ssaapi/test/java/chainmembercall_test.go
common/yak/ssaapi/test/java/java_topdef_use_and_def_chain_test.go
common/yak/ssaapi/test/syntaxflow/recursive_config_test.go
common/yak/ssaapi/test/syntaxflow/syntaxflow_use_and_def_chain_test.go
common/yak/ssaapi/test/yak/exclusive_fullchain_test.go

`topdef` and `bottom-use`  中appendDependon和appendEffectOn重复使用，导致关系冗余。
应该：
- newValue的时候进行添加append，其它的时候都不进行append

fix(ssaapi):fix some incorrect appendOn and dependOn relationship

---

common/simulator/exports.go
common/simulator/simple/config.go
common/simulator/simple/constructor.go
common/simulator/simple/element.go
common/simulator/simple/page.go

config新增leakless
代码优化
（更新信息可以不写这个 满足客户需求更新的组件）

feature(simulator): add new config

---

common/crawlerx/action.go
common/crawlerx/config.go
common/crawlerx/element.go
common/crawlerx/exports.go
common/crawlerx/main.go
common/crawlerx/main_test.go
common/crawlerx/starter.go
common/simulator/data.go
common/simulator/main.go

feat(crawlerx): add new input & click check params

---

common/coreplugin/base-yak-plugin/修改 HTTP 请求 Cookie.yak
common/coreplugin/base-yak-plugin/修改 HTTP 请求 Header.yak
common/coreplugin/base-yak-plugin/修改 HTTP 请求.yak
common/coreplugin/base-yak-plugin/多认证综合越权测试.yak

影响插件:
- 多认证综合越权测试
- 修改HTTP请求Cookie
- 修改HTTP请求Header
- 修改HTTP请求

feat(coreplugin): 使用ui-schema美化

---

common/consts/global.go
common/consts/pprof.go
common/coreplugin/base-yak-plugin/引擎性能采样自动分析.yak
common/coreplugin/base-yak-plugin/核心引擎性能采样.yak
common/coreplugin/coreplugin.go
common/utils/pprofutils/auto_analyze.go
common/utils/pprofutils/exports.go
common/utils/pprofutils/metrics.go
common/utils/pprofutils/metrics_test.go

https://github.com/yaklang/yakit/pull/2238

feat(pprof):add auto analyze script

---

.github/workflows/essential-tests.yml
common/ai/aid/aitool/buildinaitools/yakscripttools/base_test.go

ref with 
* [modify yak script name commit](https://github.com/yaklang/yaklang/commit/2879403f49aaa54e5c853f48d35e186aac2770c9#diff-258229a9db79d292293b83cfdf8b8d79f3df1d48823f18a4658de761a2b639cb)
* [check ai tool name with testcase](https://github.com/yaklang/yaklang/commit/e204dcd05930c47cf7d5ee0ca582102cf60fe2cb#diff-ae7313bf705db020ef566b6d599c9ba2c662c5c2352209846d744270d01795e4)

fix(aitool):modify yak script tools with aitool name

---

common/yakgrpc/yakgrpc.proto
common/yakgrpc/yakit/ssa_program.go
common/yakgrpc/ypb/yakgrpc.pb.go

ref https://github.com/yaklang/yakit/pull/2569

fix(grpc):program return total risk number

---

common/utils/fileparser/excelparser/excel_writer.go
common/utils/fileparser/excelparser/excel_writer_test.go
common/utils/fileparser/excelparser/exports.go
common/yak/script_engine.go

添加了完整的 Excel 文件写入功能，包括创建、编辑和保存 Excel 文件的能力。该功能与现有的 Excel 解析功能互补，提供了完整的 Excel 文件处理能力。
- 
- CreateExcelFile() - 创建新的 Excel 文件
- SaveExcelFile() - 保存 Excel 文件到指定路径
- 
- WriteCell() - 向指定单元格写入数据
- SetFormula() - 设置单元格公式
- 
- NewSheet() - 创建新工作表
- DeleteSheet() - 删除工作表
- SetSheetVisible() - 设置工作表可见性
- 
- CreateStyle() - 创建单元格样式
- SetCellStyle() - 应用样式到单元格
- 
- InsertImage() - 在工作表中插入图片
- 
- 添加了完整的测试用例，验证所有写入功能正常工作。
- 测试了与现有 Excel 解析功能的集成兼容性。
- 验证了创建的文件可以被正确解析。
- 
- 所有函数都包含参数有效性检查。
- 保持与 excelize 库一致的错误处理方式。
- 提供简洁明了的 API 接口，易于使用和维护。

feat: 添加了excel写入等功能

---

common/yak/ssa/member_call_util.go
common/yak/static_analyzer/test/basic_error_test.go

fix map member acc check false positive when map type is OrType which means subtypes should perform check as well

fix map member acc check false positive when map type is OrType which means subtypes should perform check as well

---

common/ai/aid/aicommon/emitter.go
common/ai/aid/aicommon/timeline.go
common/ai/aid/aicommon/toolcall.go
common/ai/aid/aireact/invoke_plan_and_execute.go
common/ai/aid/aireact/invoke_toolcall.go
common/ai/aid/task_call_tool.go

- Fix missing indexid in summary messages bug
- Fix YOLO mode stuck issue
- Fix PopEventProcesser shallow copy bug
- Fix memory condensation infinite recursion bug
- Fix AgreePolicy option not taking effect bug

Fix multiple AI react bugs
