yaklang/yaklang

- common/yak/cmd/yak.go
go1.19 给exec包加了点安全机制 https://pkg.go.dev/os/exec#hdr-Executables_in_the_current_directory
这导致了原有的安装脚本无法执行，报错 “cannot run executable found relative to current directory”
加了个err检查，由于yak获取这个路径并不是用来执行文件的，所以go1.19这个修改要防的安全问题在这个场景下并不存在
> fix installing yaklang on windows failure

- common/yak/antlr4yak/yakast/listener_test.go
- common/yak/antlr4yak/yakast/visitor.go
- common/yak/antlr4yak/yakast/visitor_test.go
- common/yak/antlr4yak/yakvm/vm_exec.go
实现yak源码与opcode的对照查看功能，具体效果见测试用例。
显示的格式如下
```
func sum(a) {
2:2->8:2         0:OP:pushleftr  1
2:2->8:2         1:OP:push       function params[1] codes[32]
func sum(a) {
2:14->8:2        0:OP:new-scope  3
result = 0
3:12->3:12       1:OP:push       0
3:12->3:12       2:OP:list       1
3:3->3:8         3:OP:pushleftr  3
3:3->3:8         4:OP:list       1
3:3->3:12        5:OP:assign
```
方便查看vm的代码生成
> 添加对照显示源码和opcode的功能，实现类似code的map功能

- common/utils/lowhttp/vulinbox_agent.go
- common/utils/utils.go
- common/vulinbox/route.go
- common/vulinbox/service_wsagent.go
- common/vulinbox/vul_server.go
- common/vulinbox/wsagent_proto.go
- go.mod
- go.sum
给 vulinbox agent websocket 规定了协议格式，主要分为两种
- ACTION-ACK格式
- 订阅格式
ACTION-ACK 格式用于命令 vulinbox 发送一些数据包，ACK 用于确认成功或者回传err
订阅格式即订阅，比如 vulinbox 收到的所有 http 包
> vulinbox agent websocket protocol

- common/yak/antlr4yak/executor_test.go
- common/yak/antlr4yak/yakvm/vm_exec.go
* set function scope when this scope not set  (when build function).
* don't set function scope in other time (such as assign variable from a function variable)
> fix/vm/closure_assign  check if func.scope == nil?

- common/yak/yaklib/codec/sm2_test.go
Use multiple attempts to reduce the issue of test failures caused by generating incorrect private keys for unknown reasons
> fix(sm2):sm2 test failure

- .github/workflows/essential-tests.yml
不同分支的 actions cache 是独立的，但是新签出的分支能继承原先的分支的 cache。
让ci在pr closed的时候也运行，确保：分支rebase后能过ci，main分支有cache给其他分支继承。
> ci: cache 优化

- common/yak/antlr4yak/yakast/misc.go
- common/yak/ssa/range.go
> fix(get endtoken line and column) handler "\n" in end token

- common/yakgrpc/grpc_fuzzer.go
- common/yakgrpc/grpc_fuzzer_test.go
根据后端匹配器逻辑，应当支持如下这种匹配，现在由于覆盖变量导致出现 bug
对应的 tpl 大致如下
```yaml
variables:
r1: "{{rand_int(1000, 9999)}}"
r2: "{{rand_int(1000, 9999)}}"
r3: "{{ int(r1) + int(r2)}}"
http:
- method: GET
path:
- '{{BaseURL}}/'
matchers-condition: and
matchers:
- type: word
words:
- '{{r3}}'
```
> fix(fuzzer-matcher) match predefined variables bug

- common/yak/antlr4yak/yakvm/scope.go
> fix(yakvm):Scope-idToValue Missing mutex

- common/domainextractor/extractdomain.go
- common/domainextractor/extractdomain_test.go
- common/yakgrpc/grpc_httpflow_test.go
- common/yakgrpc/grpc_mitm.go
- common/yakgrpc/yakit/httpflow.go
优化 HTTPFlow 查询的行为
1. 在大 Response / Request 的时候，不查询 Body
2. 新增 database 之外的字段用来标记大数据包
3. 保持了对 `full` 的兼容性
> impr large httpflow

- common/crep/mitm_hijack_handler.go
起初只是从 history 发送到 web fuzzer 的时候没有勾上 https 的简单问题
定位下来发现塞到数据库的 http_flow 就有问题
测试发现，mitm 使用 HTTP 代理时，存进数据库一定不是 https，socks5 我用不了，ws 不会有这个问题
isHTTPS 是根据是否有 requestOrigin.TLS 判断的，而 requestOrigin.TLS 是根据 conn 的类型判断的，但是在上述情况下这个 conn 永远都不是 *tls.Conn 
看上去这个 conn 是那个 http proxy 代理本身的 conn
先检查个 schema 补救一下
> fix(mitm): isHTTPS always false when using HTTP Proxy

- common/utils/retry.go
- common/yakgrpc/grpc_mitm.go
- common/yakgrpc/grpc_mitm_replacers.go
- common/yakgrpc/yakit/extracted_data.go
- 写入流量和染色尽可能合并成一个事务（染色超时则降级到独立事务）
- 写数据库的重试改为指数退避
- 分离染色的逻辑和存储过程
> pref(mitm): hookcolor db

- common/crawlerx/main.go
awvs目标网站带cookie爬虫测试时发现渗透目标跳转到/login下带cookie访问仍然需要输入用户名密码
修改为在遇到同scheme和host的跳转时 对原目标url进行爬虫 而不是跳转后的url
> fix(crawlerx): fix cookie unset on code 302

- common/yak/ssa/extern_instance.go
- common/yak/ssa/type.go
- common/yak/ssa4analyze/type_check.go
- common/yak/yak2ssa/ssa_error_test.go
所有外部数据都保存在Map中，所有引用都是指针, 当类型在某处被修改时，导致同类型的其他使用位置都会出现错误。
* 将Variadic从ObjectType中删除，外部类型只在创建时修改，解决互相修改的问题。
* 该Variadic保存到FunctionType中，并在FunctionType手动处理参数的打印。
> fix[ssa] fixup extern type map 

- common/yak/yaklib/codec/gbk.go
修复判断gbk编码时 最后只剩一位时无法进行双字节判断的panic
> fix(codec): gbk check panic fix

- common/minimartian/lowhttp_exec.go
- common/minimartian/mitmloop.go
- common/minimartian/proxy.go
- common/utils/lowhttp/exec.go
使用 sync map 缓存是否支持 h2 的站点可能有待商榷
> 修复mitm下 h2 不生效，修复 gmtls 和 h2 同时勾选下的 ErrUnexpectedEOF

- common/yak/ssa/type.go
- common/yak/ssa4analyze/type_inference.go
- common/yak/yak2ssa/ssa_error_test.go
> Fixup [ssa4analyze] check key type in getField method

- common/minimartian/s5.go
漏洞成因在于：是否需要认证完全决定于客户端握手时的method，这意味着客户端可以决定是否需要认证（即是否携带密码），这实际上是不合理的，应该以yakit是否设置了认证为准
> fix(mitm-socks5): socks5 auth not work

- common/yak/ssa/type.go
- common/yak/yak2ssa/ssa_error_test.go
support the nil assign to other support type: codec.AESCBCEncrypt( key, payload,nil)[0]
> fixup(ssa_type) nil assign to types

- common/pcapx/pcaputil/reassembly.go
修复前 onFrame 总是会留下最后一个 Frame 而没把他发到 reassembled
> fix: missing last frame in DataFrameReassemble

- common/utils/cli/cli.go
- common/yakgrpc/grpc_execYak.go
fix problem of yak engine parse args is not work when use script such as yak example.yak --name xxx
> fix problem of yak engine parse args 

- common/yak/ssa/call.go
- common/yak/ssa/return.go
- common/yak/ssa/ssa.go
- common/yak/ssa/ssautil/phi.go
- common/yak/ssa/type.go
- common/yak/ssa/use.go
- common/yak/ssa4analyze/type_check.go
- common/yak/ssaapi/ssatest/utils.go
- common/yak/static_analyzer/test/basic_error_test.go
- common/yak/yak2ssa/builder_ast.go
- common/yak/yak2ssa/test/real_yak_test.go
- 在SSA处理OOP的时候将会将成员访问设置到参数，并转换为额外的参数传入，以达到在函数调用时进行成员变量的获取的效果。但是这样的处理将会导致函数出现多余的参数，因此需要保留原本函数定义中的预期参数个数。
- 在循环中，函数的PHI替换将会导致函数调用语句定义改变，因此需要在Call指令的Method被替换时进行修正。
> [Fix] ssa parameter length

- common/crawlerx/check.go
- common/crawlerx/check_test.go
修复当目标url不以"/"结尾时，子域名扫描范围判断错误的bug
> fix(crawlerx): fix subdomain scan range not work in some cases

- common/utils/lowhttp/poc/poc.go
文档介绍 poc 请求默认超时时间为 15 秒
+ https://yaklang.io/docs/api/poc/#timeout
+ https://yaklang.io/docs/api/poc/#connecttimeout
实测为 1.5秒
代码写的是 1500毫秒
```go
defaultTimeout     = time.Duration(1500) * time.Millisecond
```
修改后正常
实际使用场景 1.5 秒太容易超时了，然后使用者如果 `resp, _, _ = poc.xx`，忽略异常的话会很无感， 直接请求什么反应都没有
> fix(poc): modify the default poc http timeout

- common/utils/netutil/routewrapper/routewrapper_test/command_test.go
- common/utils/netutil/routewrapper/routewrapper_windows.go
In routewrapper_windows.go, at 634:91, It prints int as %s which will cause error
> fix(routewrapper): replace %s with %v in error message

- common/fuzzx/request_params.go
> json fuzz 参数传递错误

- common/yak/ssaapi/analyze_context.go
- common/yak/ssaapi/analyze_cross_process.go
- common/yak/ssaapi/exclusive_z_bottom_use.go
- common/yak/ssaapi/exclusive_z_top_defs.go
- common/yak/ssaapi/test/syntaxflow/syntaxflow_cross_process_test.go
- common/yak/ssaapi/test/syntaxflow/top_user_recursive_test.go
- recover cross process should not clear the visited map
- the hash of from which is call should include `object context`
> fix(ssaapi):recover cross process should not clear the visited map

- common/syntaxflow/sfvm/frame.go
- common/syntaxflow/sfvm/visitor.go
- common/yak/ssaapi/sf_value.go
- common/yak/ssaapi/sf_values.go
所有语句都保存在Statement的Opcode中，出现错误将会被跳过而非停止整个规则。
影响一下三种语句：
* description语句将不会出现错误，
* check语句的快速失败模式包裹了criticalError，
* fileFilter也应该跳过而非停止。
> fix(syntaxflow):all statement should wrap in statement opcode

- common/coreplugin/base-yak-plugin/SSA 项目编译.yak
因为太多人误填database path，导致进度条卡住。后续切换数据库的机制会进行重构，支持多个数据库，因此现在暂时注释掉这个database path。
> fix(core-plugin):check database path for `SSA 项目编译.yak`

- common/yakgrpc/yakit/httpflow.go
- common/yakgrpc/yakit/httpflow_test.go
FuzzSearchWithStringArrayOrAf函数只对搜索项左模糊匹配，导致形如`YAKIT_COLOR_GREEN|SQL注入测试点`的tags匹配失败
> fix http flow color filter

- common/vulinbox/service_websocket.go
vulinbox默认的websocket靶场是服务端一直返回固定的信息，导致用户不知道websocket fuzzer发送的信息是否生效。现在改成返回的是用户发送的信息。
> fix(vulinbox):websocket-case should use user requests as feedback

- common/utils/memedit/editor.go
- common/yak/java/java2ssa/builder_prehandler.go
- common/yak/java/template2java/tempate2java.go
- common/yak/ssa/database_code.go
- common/yak/ssa/database_offset.go
- common/yak/ssa/ssadb/offset.go
- common/yak/ssa/ssadb/source.go
- common/yak/ssa/ssadb/source_filesys.go
- common/yak/ssa/ssadb/source_filesys_test.go
- common/yak/ssaapi/ssa_compile_init.go
- common/yak/ssaapi/test/yak/compile_db_test.go
- common/yakgrpc/language_server.go
ircode只使用文件内容作为hash，会导致不同项目相同文件内容文件hash一样。进而导致ircode的位置会乱掉。
- 使用项目名+路径+文件内容作为hash
> fix(ssa):fix error hash for source code

- common/crep/mitm.go
- common/crep/mitm_config.go
- common/minimartian/mitm/mitm.go
- common/minimartian/mitm/obsolete_tls.go
- common/yakgrpc/grpc_mitm_test.go
这里有个特殊情况，如果用户提供的或者自己设置的国密CA证书其实是一个RSA证书这种情况下浏览器与MITM握手时在利用CA证书签名国密证书时会报错`gmtls-handshake error: x509: requested SignatureAlgorithm does not match private key type`此时如果客户端支持fallback则可正常回退到常规tls
> allow MITM start with invalid GM cert or nil GM cert

- common/ai/rag/hnsw/graph.go
- common/ai/rag/hnsw/hnsw_test.go
- common/ai/rag/sqlitedb_store_hnsw.go
- Separate neighbor deletion and replenishment in isolate() method to avoid concurrent modification issues
- Add comprehensive test to verify deleted nodes are properly removed from neighbor maps
> fix: Fix HNSW node deletion neighbor cleanup bug

- common/ai/aid/aicommon/emitter.go
- common/ai/aid/aicommon/toolcall.go
- common/ai/aid/aireact/config.go
- common/ai/aid/aireact/invoke_toolcall.go
- common/ai/aid/task_call_tool.go
- Fix Emitter's PushEventProcesser bug caused by shallow copy of eventProcesserStack pointer that modified original emitter's stack when pushing handlers, now performs deep copy of eventProcesserStack
- Fix ToolCaller bug where modifying emitter in onStart was ineffective (this bug worked in combination with the previous bug, making it hard to detect)
- Add AIReact event persistence to database
- Fix AIReact tool call history retrieval failure
> fix: unable to get tool call details by calltoolid
